### ISSUE TITLE
"suppressionGroupId" as parameter of Client.Campaigns.CreateAsync should be nullable long.

### ISSUE THREAD

**Issue by yofang** [Jericho/StrongGrid#103]
I believe this is a typo in code.
Simply missing a question mark after datatype long.

**Comment by Jericho** [comment]
Actually, this was intentional. I explain the reason for this decision in #46

**Comment by Jericho** [comment]
I read the other ticket you created #104 where you mention:

> SendGrid Api responded an error, saying I should only applied one of { suppressionGroupId, customUnsubscribeUrl }

If I understand this correctly, this means that SendGrid allows you to omit the suppressionGroupId if you provide a customUnsubscribeUrl. I was not aware of this. This is a pretty strong argument for allowing the suppressionGroupId to be omitted when invoking Campaings.CreateCampaign

**Comment by Jericho** [comment]
I did a few tests and confirm that SendGrid allows you to omit the suppression group if you specify the unsubscribe Url. Therefore, the `suppressionGroupId` parameter in the CreateCampaign method should be optional. I will release a hotfix shortly.

Please note: I will have to change the order of parameters on the CreateCampaign (because optional parameters must be listed after mandatory parameters) which means this hotfix release will contain breaking changes. I will also change the order of the parameters on the UpdateCampaign method to be consistent with CreateCampaign.

**Comment by yofang** [comment]
Thank you. As SendGrid mentioned: "[Either suppression_group_id or custom_unsubscribe_url may be set/used, but not both. Please remove one before setting the other.](https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/campaigns.html#Create-a-Campaign-POST)". So, when make call, user will need to pick one of the two, suppressionGroupId and customUnsubscribeUrl.
