### ISSUE TITLE
Invalid cast exception when parsing floating point timestamps

### ISSUE THREAD

**Issue by Jericho** [Jericho/StrongGrid#125]
This issue was reported by @Liversage and he submitted PR #124 to resolve the problem.

This issue occurs when SendGrid returns an 'epoch' date with decimal like this: `"send_at": 1487700692.41447`. We currently cast the JSON data to a `long` which causes the invalid cat. His solution is to cast the data to a `double`.

**Comment by Liversage** [comment]
The solution is actually to **convert** (not cast) the data to `double`. The `reader.Value` property is an `object` so it might contain a `long` or a `double` depending on the format of timestamp in the JSON. Casting to another type (e.g. `long` when the value is a `double`) throws the exception.

Sorry for the nitpicking but I wanted to make sure that the underlying problem was well described. I'm very delighted to see the swift turnaround time on this issue.

**Comment by Jericho** [comment]
Fair enough. I corrected my description of your solution.
