### ISSUE TITLE
StrongGrid.Model.MailAddress is not CLS-compliant

### ISSUE THREAD

**Issue by aptbid2005** [Jericho/StrongGrid#171]
I'm making available Recipient and Sender parameters in my classes constructor. I'm making those types StrongGrid.Model.MailAddress and I'm getting the error that StrongGrid.Model.MailAddress is not CLS-Compliant.

Here's the stub for my ctor.

public EmailRouter(StrongGrid.Model.MailAddress Recipient, StrongGrid.Model.MailAddress Sender, string Subject, string Body){ }

Could it be possible to make the solution CLS-Compliant by adding the tag to the assembly and republishing to NuGet?

**Comment by Jericho** [comment]
I could investigate what it would take to ensure the library is CLS compliant (I'm sure there's more to it than simply adding an assembly tag, but to be honest I'm not certain). In the mean time let me make a recommendation:

I think it would be better to avoid "leaking" model classes from the `StrongGrid` library from your class so that people using your `EmailRouter` class don't have to learn about the StrongGrid classes. What I would do in your case is to use the `System.Net.Mail.MailAddress` for the parameters in your class constructor and I would convert the mail addresses into the appropriate StrongGrid class in your constructor. What I have in mind is something like this:

```csharp
public EmailRouter(System.Net.Mail.MailAddress Recipient, System.Net.Mail.MailAddress Sender, string Subject, string Body)
{
    // Convert the System.Net.Mail.MailAddress into StrongGrid.Model.MailAddress
    var to =  new StrongGrid.Model.MailAddress(Recipient.Address, Recipient.DisplayName);
    var from = new StrongGrid.Model.MailAddress(Sender.Address, Sender.DisplayName);

    ... the rest of your code ...
}
```

Hopefully this makes sense.

**Comment by aptbid2005** [comment]
ok, I will try that tomorrow when I get to work. thanks for your answer.

**Comment by Jericho** [comment]
I invested some time today researching what would be necessary to make `StrongGrid` CLSCompliant and turns out it would involve a number of breaking changes. There are a few classes and methods that would need to be `internal` (instead of `public`) because some of their parameters are not CLSCompliant. Specifically:  
- `DiagnosticHandler`
- `SendGridErrorHandler`
- Extension methods
- The constructor for the resource classes (such as ApiKeys, Alerts, Mail, etc.)

There are also a number of classes currently marked as `public` but they were never intended to be used publicly such as `CategoryConverter`, `CustomFieldConverter`, `SendGridRetryStrategy`, etc. Therefore I'm thinking about making them `internal`.
