### ISSUE TITLE
Contacts.SearchAsync listId should be long

### ISSUE THREAD

**Issue by tmacht** [Jericho/StrongGrid#214]
The listIds that are returned by Campaigns.GetAsync are long, but the listId that is passed to Contacts.SearchAsync is int. I think that it should also be long?

**Comment by Jericho** [comment]
Yes indeed, it should be long.

**Comment by Jericho** [comment]
In fact, I tried to be consistent and use `long` for all identifier fields (such as Alert.Id, Campaign.Id, CustomField.Id, List.Id, etc.) but this issue you are raising motivated me to review all model classes and I discovered that I was not always consistent. I found a few instances where I used `int` instead of `long`. 

I will document all instances below and will fix all of them:
- [ ] Field.Id
- [ ] SubUser.Id
- [ ] Suppression.GroupId
- [ ] SuppressionGroup.Id
- [ ] UnsubscribeOptions.GroupId
