### ISSUE TITLE
JsonProperty incorrect for IpPool Name

### ISSUE THREAD

**Issue by rlightner** [Jericho/StrongGrid#240]
It should be `pool_name`

https://github.com/Jericho/StrongGrid/blob/9190deb52f4f5d7f72ba2a6d37d277d3a6fc20a2/Source/StrongGrid/Models/IpPool.cs#L16

```json
{
  "ips": [
    {
      "ip": "1.1.1.1",
      "start_date": null,
      "warmup": false
    }
  ],
  "pool_name": "MyPoolName"
}
```

**Comment by Jericho** [comment]
When creating a new IP pool, SendGrid returns a JSON string with a `name` property. Same situation when retrieving multiple IP pools and again same situation when updating an existing pool.

However, as you pointed out, the property is called `pool_name` when retrieving a single IP pool. I had not noticed that!

I need to think for a minute how I'm going to handle the fact that the name property is not consistently named.

**Comment by Jericho** [comment]
**A few observations:**

_Observation 1:_

When invoking `IpPools.RetrieveAllAsync`, you expect to retrieve the information about all existing pools. In fact the documentation states: 

> This endpoint allows you to retreive all of your IP pools.

In reality, what SendGrid returns is an array of objects each with a single property called `name` like this:
```
[
  {"name":"StrongGrid Integration Testing: new pool"},
  {"name":"StrongGrid Integration Testing: updated name"}
]
```

In other words: you only retrieve the names of your pools. Therefore, I think it would be more appropriate for the `IpPools.GetAllAsync` method to return an array of strings rather than an array of `IpPool` objects. To make it even more clear, I should probably rename this method to `GetAllNamesAsync`.  Let me know if you agree.

_Observation 2:_

When creating a new pool, SendGrid responds with a JSON string such as: `{"name":"StrongGrid Integration Testing: new pool"}`. Again, the only useful information is the `name` property, there is no additional information about the newly created pool. Therefore I'm questioning why the `IpPools.CreateAsync` method would return `Task<IpPool>`. I think I should change the signature of this method to simply return `Task`. Let me know if you agree.

_Observation 3:_

Assuming we are in agreement regarding observation 1 and 2, it would mean that the only method that would need to parse JSON into a `IpPool` object is when retrieving a single pool and in this scenario the name of the property containing the name of the pool is, as you pointed out, `pool_name`.

**Comment by rlightner** [comment]
I agree with all those for the most part.

When creating a pool, they return the name that was created, so I would like that returned from the `IpPools.CreateAsync` as well, as I can then flow that through my system if needed.

Same goes with any other `Put`/`Post` methods.

**Comment by Jericho** [comment]
So: `CreateAsync` should return a string containing to name of the new pool which is the name you just provided to the CreateAsync method. Doesn't that seem redundant to you?

**Comment by Jericho** [comment]
Personally, I would write something like this:
```
var poolName = "My Pool";
await strongGridClient.IpPools.CreateAsync(poolName, cancellationToken).ConfigureAwait(false);
```
which means that I would not need CreateAsync to return the name.

**Comment by rlightner** [comment]
Looks great!

**Comment by Jericho** [comment]
Perfect I'll go with that. Working on it right now. I'll try to publish hotfix tonight, or tomorrow at latest.

**Comment by rlightner** [comment]
Thanks for the effort!
