### ISSUE TITLE
Are Substitutions supported when using dynamic template?

### ISSUE THREAD

**Issue by StefH** [Jericho/StrongGrid#256]
You say:
When using a "dynamic" template, you must surround merge fields with double curly brackets such as {{first_name}} but substitutions must OMIT the curly brackets.
``` C#
new MailPersonalization
{
    To = new[] { new MailAddress("test@example.com", "John Smith") },
    Substitutions = new KeyValuePair<string, string>[]
    {
        new  KeyValuePair<string, string>("first_name", "Bob")
    }
}
```

However in your code:
``` c#
/// <summary>Gets or sets the substitutions.</summary>
    /// <value>The substitutions.</value>
    /// <remarks>
    /// This is used when sending emails without a template or when using a 'legacy' template.
    /// Substitutions are ignored when using a dynamic template.
    /// For dynamic templates, you must use <see cref="P:StrongGrid.Models.MailPersonalization.DynamicData" />.
    /// </remarks>
```

So my email template looks like:
``` html
<div>Beste {{ClaimApproverName}},</div>
```

And my C# code looks like:
``` c#
public class EmailTemplateData
{
    public string ClaimApproverName { get; set; }
}
```

``` c#
var personalizations = toAddresses.Select(to =>
                new MailPersonalization
                {
                    // Define to Address
                    To = new[] { new MailAddress(to.Address, to.Name) },

                    // Define Substitutions
                    Substitutions = new[]
                    {
                        new KeyValuePair<string, string>("ClaimApproverName", to.Name)
                    },
                    DynamicData = emailTemplateData
                }
            );
```

However the email not having the `ClaimApproverName` substituted?

**Comment by Jericho** [comment]
You're referring to a note I wrote last July on ticket 236 where I describe how to specify data when using dynamic templates. At the time the code sample was accurate because StrongGrid only supported basic merge field replacement and `Substitutions` could be used for that purpose. However, things have changed since then and StrongGrid now supports much more advanced scenarios such as iterable items, deep objects, etc. In order to support these more advanced features I had to abandon using `Substitutions` in favor of the more flexible `DynamicData`. That's why the comment you included in your question says:
> Substitutions are ignored when using a dynamic template. For dynamic templates, you must use DynamicData.

The [Dynamic template section](https://github.com/Jericho/StrongGrid#dynamic-templates) in the readme contains the most accurate code samples.
