### ISSUE TITLE
More Information on IP Warmup 

### ISSUE THREAD

**Issue by toddca** [Jericho/StrongGrid#290]
I see the example code you have included however I am not sure how you package and execute that code. For example, should we put this into a console app and run it and then have it keep running for days at a time, or is there another way we should be doing this?

**Comment by Jericho** [comment]
Thanks for the question. 

First, let me say that the motivation for writing the warmup engine was to provide an alternative to SendGrid's built-in warmup logic. As you are probably aware, SendGrid's logic can warmup your account and/or new IP addresses, it's built in their platform (which makes it very convenient) but it's not configurable and it works only if you are sending emails on a daily basis. This very basic warmup logic can't handle scenarios where you sometimes skip a day, or maybe you are sending only a few time a week or maybe even only once a week.

The StrongGrid warmup engine is much more advanced and allows you to configure your sending schedule (AKA 'reset days' in SendGrid's lingo) and it also allows you to define your custom daily email volume if you don't want to use the default daily volume defined by SendGrid. The biggest advantage of using StrongGrid's warmup engine is that it's based on "sending" days instead of "calendar" days. Let me illustrate: let's say that you send emails every other day (Monday, Wednesday, Friday, etc.). In this scenario, Monday would be your first warmup day, Wednesday would be your second warmup day, Friday would be your third warmup day, etc. If you were to use SendGrid's default logic, Monday would be your first warmup day, Tuesday would be considered your second day despite the fact that in our hypothetical scenario you are not sending any email on Tuesday and Wednesday would be your third day. This means that on Wednesday (which is your second day of sending emails but SendGrid considers to be your third day) SendGrid's logic would allow your to send a significantly larger number of emails and ISPs would see this spike in volume as "suspicious" and therefore would lower the reputation associated with your IP address. I hope this contrived example helps understand the motivation for writing this warmup engine.

Having said all this, let me try to answer your question. You don't need to keep StrongGrid's warmup engine running for days or anything. You simply instantiate it and invoke one of the following methods when you need to send emails:

```
var result = warmupEngine.SendToSingleRecipientAsync(...);
var result = warmupEngine.SendToMultipleRecipientsAsync(...);
var result = warmupEngine.SendAsync(...);
```

The result will indicate when the warmup is successfully completed and at that time you no longer need to use the engine, you can simply send emails using the standard method:
```
client.Mail.SendToSingleRecipientAsync(...)
client.Mail.SendToMultipleRecipientsAsync(...);
client.Mail.SendAsync(...);
```

While you are warming up your IP addresses, the engine automatically keeps track of your progress. The progress is saved to a file and the next time you invoke one of it's methods it will retrieve and update the progress. This process is repeated until the warmup is successfully completed.

I hope this answers your question.

**Comment by toddca** [comment]
Thank you very much for this additional information. I am set now.

**Comment by Jericho** [comment]
You're welcome. Let me know how it goes. To be honest I haven't gotten any feedback on the Warmup engine so I welcome any comments.
