### ISSUE TITLE
exception when calling ParseInboundEmailWebhook

### ISSUE THREAD

**Issue by gregveres** [Jericho/StrongGrid#303]
Hi,

I am using the ParseInboundEmailWebhook and when I call it, I get the following exception:

**exception:**
{"Could not load file or assembly 'HttpMultipartParser, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"HttpMultipartParser, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null"}

**file name:**
"HttpMultipartParser, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null"

**Message:**
"Could not load file or assembly 'HttpMultipartParser, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

**target site:**
{StrongGrid.Models.Webhooks.InboundEmail ParseInboundEmailWebhook(System.IO.Stream)}

It seems that ParseInboundEmailWebhook is trying to load the HttpMultipartParser dll and that is failing. I think it is failing because you are specifying the public token is null, but the dll is signed. 

Am I reading that correctly?

**Comment by gregveres** [comment]
Ok, a little more investigation revealed some more details:
StrongGrid is compiled against HttpMultipartParser v2.2.1.0, which is not signed. 
I had upgraded, assuming that it was a minor update, to v2.2.4.0. But that version is now signed and fails to load properly.

I think StrongGrid should upgrade to the newer version. 

There might also be a way to use a binding redirect to get around the problem. But for now I just downgraded back to v2.2.1.0 because I don't use the library anywhere else in my code.

**Comment by Jericho** [comment]
Sounds similar to [this issue](https://github.com/Jericho/StrongGrid/issues/255) where the person had also referenced a more recent version of HttpMultipartParser than what StrongGrid was designed to work with. Truly, there is no reason for you to reference a more recent version so I am curious why you felt the need to upgrade the reference.

Having said that, it so happens that I am currently working on the next version of StrongGrid which will reference HttpMultipartParser version 3.0.0 because new functionality was introduce in that newer release.

**Comment by gregveres** [comment]
Yes it is the same issue. I didn't see that one since it was closed. Sorry about that. 

When I installed StrongGrid using NuGet, it brought in a few packages. HttpMultipartParser was one of those. Then, since it is now a package that is part of my project, I get messages that it is out of date and there is an update for it. 

I view updates like warnings in the code. If you have them and don't deal with them, they can cover up the real problems (ie, packages that really need to be upgraded because of security vulernabilities etc). So when it showed up as an upgrade option, I upgraded. 

The real issue is that because the dll is demand loaded, it didn't show up as a problem until run time. We caught it while doing final deployment testing before pushing the system to production. 

I have solved my problem by backing up to version 2.2.1 and I will live with NuGet telling me that I have an update available for it.

BTW, I like the package. It is the webhook processing that drew me to StrongGrid over using SendGrid's library directly. Thank you for all the effort you have put into it and continue to put into it!

**Comment by Jericho** [comment]
You're welcome and I appreciate your feedback. I have invested a lot of effort (and hours!) in this library and the only reward I get is when people tell me they get value out of it. Makes me feel like my effort was worth it!

Since you use the webhook parser, you'll be interested to know that the [improvement](https://github.com/Jericho/StrongGrid/issues/300) I'm working on  for the next release is an `async` version of the inbound email parser.

**Comment by gregveres** [comment]
Yea having the parse be async would be helpful. All of our stuff is async where it can be. 
And I definitely appreciate  your effort!

**Comment by Jericho** [comment]
FYI: version 0.62.0 has been released.
