### ISSUE TITLE
dotnetcore 3.1

### ISSUE THREAD

**Issue by filoe** [Jericho/StrongGrid#307]
dotnetcore 2.2 runs out of support.
https://dotnet.microsoft.com/platform/support/policy/dotnet-core

Is there any chance to support dotnetcore 3.1 soon?
Or to put in another way: Why does the readme states that dotnetcore 2.0 is support but the nuget package support only requires netstandard 2.0 which is supported by dotnetcore 3.1?

**Comment by Jericho** [comment]
> Why does the readme states that dotnetcore 2.0 is support but the nuget package support only requires netstandard 2.0 which is supported by dotnetcore 3.1?

Because at the time the passage you are referring to was written, dotnetcore 2.0 was the only framework supporting netstandard 2.0. Things have changed since then: new versions of the framework have been released and, as you point out, netcore 3.x also supports netstandard 2.0 but the readme was not updated.

**Comment by Jericho** [comment]
How about something like this:

StrongGrid supports the `4.6.1` .NET framework as well as any framework supporting `.NET Standard 2.0` (which includes `.NET framework 4.7.2`, `.NET framework 4.8`, `.NET Core 2.x`, `.NET Core 3.x`, `ASP.NET Core 2.0` and `ASP.NET Core 3.x`).

**Comment by filoe** [comment]
Perfect, was just not sure about whether it supports .net core 3.0 or not.
