### ISSUE TITLE
Line Breaks in Parsed Text

### ISSUE THREAD

**Issue by deansilkyocean** [Jericho/StrongGrid#312]
Hi,
I'm having trouble preserving line breaks in Text of the email once Parsed from Sendgrid 

`Dim parser = New WebhookParser()`
`Dim inboundMail = parser.ParseInboundEmailWebhook(context.Request.InputStream)`
`emailResponse.text = inboundMail.Text`

I dont see either `/r` or html `<br />` in the parsed text.  How do I retain either of them?

Thanks

**Comment by Jericho** [comment]
Are you sure these elements are present in the web hook data?

If so, please provide a sample so I can try to reproduce.

**Comment by deansilkyocean** [comment]
I can see the spacing if I send the sendgrid webhook to a requestbin end point.  See attached screenshot
![image](https://user-images.githubusercontent.com/40138911/73340947-8e0b5100-4273-11ea-9019-6c2702d3fc1e.png)

**Comment by Jericho** [comment]
Can you share the content of the postbin to help me attempt to reproduce?

**Comment by deansilkyocean** [comment]
Hi,
Thanks for your help.  You can see the full content here - https://requestbin.com/r/enh7u74n47975/1X3ufQqPN1HBuBUHK8vxOKqFjfX
If you want to create your own then send an email to 1234-1[at]requestbin.squaremeal.co.uk

**Comment by Jericho** [comment]
Excellent, this should help. I’m away all day today so can’t investigate immediately but I’ll look into it as soon as I get back. 

Looking at the postbin I just noticed something odd: the “spam-report” section says that they include a copy of the original message and this copy does not have any line break!?!?

Just a guess on my part: is it possible your text contains ‘non-standard’ line break? Like, a lone carriage return instead of carriage return combined with line feed?

Final question: I just want to ensure there’s no confusion. You observe this problem in the text section of the email only, right? The html is fine? If so, how are you creating this text? For example, are you relying on SendGrid’s feature that auto-generates the text by stripping html tags from your html content?

**Comment by Jericho** [comment]
I just used the content of the postbin you shared and I am not observing the problem you experiencing:

![image](https://user-images.githubusercontent.com/112710/73449411-156aca00-4331-11ea-9b63-ac3c798b01b4.png)

So I'm going to need your help to figure out the specific steps to reproduce the problem.

**Comment by deansilkyocean** [comment]
Hi,
Sorry my fault.  It was returning them correctly but we were not decoding them to html correctly.  Thanks for you help.
