### ISSUE TITLE
Parsing misbehavior when display name contains angle brackets (<, >)

### ISSUE THREAD

**Issue by mohammadbadiul** [Jericho/StrongGrid#323]
When trying to parse (using `WebhookParser.ParseInboundEmailWebhook`) an inbound email from a sender with display name with angle brackets the parser returns incorrect results. For example for the following sender

`From: "Doe, John <johndoe@mail.com>" <johndoe@mail.com>`

**Expected output**
**Name:** Doe, John <johndoe@mail.com>
**Email:** johndoe@mail.com

**Actual output**
**Name:** (empty)
**Email:** "Doe, John

**Comment by Jericho** [comment]
The current email address parsing was designed to handle scenarios such as:

- Email address without a name: `bob@example.com`
- Email address with a name which may contain a coma: `Doe, John <johndoe@mail.com>`
- Email address with a name which may be surrounded by double-quotes: `"Doe, John" <johndoe@mail.com>`

But, as you point out, it does not correctly handle the scenario you are presenting. The issue is that the email address is repeated in the name part but I agree that this is a scenario that should be properly handled. I'll look into it.
