### ISSUE TITLE
can't parse default message from sendgrid

### ISSUE THREAD

**Issue by arielsrv** [Jericho/StrongGrid#333]
https://sendgrid.com/docs/for-developers/parsing-email/setting-up-the-inbound-parse-webhook/#example-default-payload

My stacktrace is:

![image](https://user-images.githubusercontent.com/760657/87208348-c2843e00-c2e4-11ea-9f3c-3705a53c917e.png)

**Comment by Jericho** [comment]
Sounds a lot like #230. 

That issue was raised almost three years ago so the details are not fresh in my memory but if I remember correctly the root of this problem was the sample payload provided in the documentation page that you linked to is not in the format expected by StrongGrid. When you configure the inbound parse webhook in your SendGrid account you are given the option to "Send Raw" which you must turn off in order for StrongGrid to be able to parse the payload but their sample happens to be in this "raw" format. Secondarily, there was also a problem with line termination caused by `curl` which I assume you are also using based on the `User-Agent` in the screenshot you posted. I provided a [better sample payload and C# code sample](https://github.com/Jericho/StrongGrid/issues/202#issuecomment-339667513) to avoid these issues. Hopefully this will help you as well.

**Comment by arielsrv** [comment]
Thanks!
