### ISSUE TITLE
Encoding error in ParseInboundEmailWebhook

### ISSUE THREAD

**Issue by BirgitteLoweJ** [Jericho/StrongGrid#341]
Hi

I got this error message while parsing an incoming email today:
"'iso-8859-10' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')"

The charset is: 
{"to":"UTF-8","subject":"UTF-8","from":"UTF-8","text":"iso-8859-10"}

**Comment by Jericho** [comment]
I am not familiar with `iso-8859-10` specifically so I'll have to do some research but my guess is that, just like the error message says, this encoding is not supported on Windows (I'm assuming you are running on Windows, is that right?). It could also be that this encoding is supported on Windows but under a different name.

**Comment by BirgitteLoweJ** [comment]
Its running in Azure set up with ubuntu-latest.

**Comment by Jericho** [comment]
Your application is .net core (2.1, 3.0, etc) as opposed to .net standard (such as 4.5, 4.6, etc.) am I right?

I'm asking because something changed in .net core: instead of querying the operating system for a list of available code pages, .net core has a hard coded list of code pages and `iso-8859-10` evidently was considered to be "not very common" and therefore not supported by .net core. This was [discussed](https://github.com/dotnet/runtime/issues/31510) last fall in the .net core repo and the conclusion (as I understand it) is that `iso-8859-10` is too uncommon to be supported by .net core.

So at this point I am not very hopeful that I will be able to help you but I will continue my research. Maybe I cna find a party library that is able to support this code page.

One final question: do you have any idea why the text was encoding with this uncommon code page? Does it contain special characters? Or maybe was it created with a special editor or email client?

**Comment by Jericho** [comment]
To be clear, 140 code pages are available in Windows when running under .net full and only 8 code pages are available when running .net core. Additionally, StrongGrid takes advantage of a bunch of "supplemental" code pages which Microsoft has provided as a separate NuGet package (see complete list below). Unfortunately, the specific code page you require is not on any of these lists so I am at a loss as to how I can help you. At this point, I welcome any suggestion.

By the way, have you been able to figure out why the email content was encoded with the "unusual" code page in the first place?

```
Code page name
---------------------------
437
arabic
asmo-708
big5
big5-hkscs
ccsid00858
ccsid00924
ccsid01140
ccsid01141
ccsid01142
ccsid01143
ccsid01144
ccsid01145
ccsid01146
ccsid01147
ccsid01148
ccsid01149
chinese
cn-big5
cn-gb
cp00858
cp00924
cp01140
cp01141
cp01142
cp01143
cp01144
cp01145
cp01146
cp01147
cp01148
cp01149
cp037
cp1025
cp1026
cp1256
cp273
cp278
cp280
cp284
cp285
cp290
cp297
cp420
cp423
cp424
cp437
cp500
cp50227
cp850
cp852
cp855
cp857
cp858
cp860
cp861
cp862
cp863
cp864
cp865
cp866
cp869
cp870
cp871
cp875
cp880
cp905
csbig5
cseuckr
cseucpkdfmtjapanese
csgb2312
csgb231280
csibm037
csibm1026
csibm273
csibm277
csibm278
csibm280
csibm284
csibm285
csibm290
csibm297
csibm420
csibm423
csibm424
csibm500
csibm870
csibm871
csibm880
csibm905
csibmthai
csiso2022jp
csiso2022kr
csiso58gb231280
csisolatin2
csisolatin3
csisolatin4
csisolatin5
csisolatin9
csisolatinarabic
csisolatincyrillic
csisolatingreek
csisolatinhebrew
cskoi8r
csksc56011987
cspc8codepage437
csshiftjis
cswindows31j
cyrillic
din_66003
dos-720
dos-862
dos-874
ebcdic-cp-ar1
ebcdic-cp-be
ebcdic-cp-ca
ebcdic-cp-ch
ebcdic-cp-dk
ebcdic-cp-es
ebcdic-cp-fi
ebcdic-cp-fr
ebcdic-cp-gb
ebcdic-cp-gr
ebcdic-cp-he
ebcdic-cp-is
ebcdic-cp-it
ebcdic-cp-nl
ebcdic-cp-no
ebcdic-cp-roece
ebcdic-cp-se
ebcdic-cp-tr
ebcdic-cp-us
ebcdic-cp-wt
ebcdic-cp-yu
ebcdic-cyrillic
ebcdic-de-273+euro
ebcdic-dk-277+euro
ebcdic-es-284+euro
ebcdic-fi-278+euro
ebcdic-fr-297+euro
ebcdic-gb-285+euro
ebcdic-international-500+euro
ebcdic-is-871+euro
ebcdic-it-280+euro
ebcdic-jp-kana
ebcdic-latin9--euro
ebcdic-no-277+euro
ebcdic-se-278+euro
ebcdic-us-37+euro
ecma-114
ecma-118
elot_928
euc-cn
euc-jp
euc-kr
extended_unix_code_packed_format_for_japanese
gb18030
gb2312
gb2312-80
gb231280
gb_2312-80
gbk
german
greek
greek8
hebrew
hz-gb-2312
ibm-thai
ibm00858
ibm00924
ibm01047
ibm01140
ibm01141
ibm01142
ibm01143
ibm01144
ibm01145
ibm01146
ibm01147
ibm01148
ibm01149
ibm037
ibm1026
ibm273
ibm277
ibm278
ibm280
ibm284
ibm285
ibm290
ibm297
ibm420
ibm423
ibm424
ibm437
ibm500
ibm737
ibm775
ibm850
ibm852
ibm855
ibm857
ibm860
ibm861
ibm862
ibm863
ibm864
ibm865
ibm866
ibm869
ibm870
ibm871
ibm880
ibm905
irv
iso-2022-jp
iso-2022-jpeuc
iso-2022-kr
iso-2022-kr-7
iso-2022-kr-7bit
iso-2022-kr-8
iso-2022-kr-8bit
iso-8859-11
iso-8859-13
iso-8859-15
iso-8859-2
iso-8859-3
iso-8859-4
iso-8859-5
iso-8859-6
iso-8859-7
iso-8859-8
iso-8859-8 visual
iso-8859-8-i
iso-8859-9
iso-ir-101
iso-ir-109
iso-ir-110
iso-ir-126
iso-ir-127
iso-ir-138
iso-ir-144
iso-ir-148
iso-ir-149
iso-ir-58
iso8859-2
iso_8859-15
iso_8859-2
iso_8859-2:1987
iso_8859-3
iso_8859-3:1988
iso_8859-4
iso_8859-4:1988
iso_8859-5
iso_8859-5:1988
iso_8859-6
iso_8859-6:1987
iso_8859-7
iso_8859-7:1987
iso_8859-8
iso_8859-8:1988
iso_8859-9
iso_8859-9:1989
johab
koi
koi8
koi8-r
koi8-ru
koi8-u
koi8r
korean
ks-c-5601
ks-c5601
ks_c_5601
ks_c_5601-1987
ks_c_5601-1989
ks_c_5601_1987
ksc5601
ksc_5601
l2
l3
l4
l5
l9
latin2
latin3
latin4
latin5
latin9
logical
macintosh
ms_kanji
norwegian
ns_4551-1
pc-multilingual-850+euro
sen_850200_b
shift-jis
shift_jis
sjis
swedish
tis-620
visual
windows-1250
windows-1251
windows-1252
windows-1253
windows-1254
windows-1255
windows-1256
windows-1257
windows-1258
windows-874
x-ansi
x-chinese-cns
x-chinese-eten
x-cp1250
x-cp1251
x-cp20001
x-cp20003
x-cp20004
x-cp20005
x-cp20261
x-cp20269
x-cp20936
x-cp20949
x-cp50227
x-ebcdic-koreanextended
x-euc
x-euc-cn
x-euc-jp
x-europa
x-ia5
x-ia5-german
x-ia5-norwegian
x-ia5-swedish
x-iscii-as
x-iscii-be
x-iscii-de
x-iscii-gu
x-iscii-ka
x-iscii-ma
x-iscii-or
x-iscii-pa
x-iscii-ta
x-iscii-te
x-mac-arabic
x-mac-ce
x-mac-chinesesimp
x-mac-chinesetrad
x-mac-croatian
x-mac-cyrillic
x-mac-greek
x-mac-hebrew
x-mac-icelandic
x-mac-japanese
x-mac-korean
x-mac-romanian
x-mac-thai
x-mac-turkish
x-mac-ukrainian
x-ms-cp932
x-sjis
x-x-big5
```

**Comment by BirgitteLoweJ** [comment]
Thanks for investigating this. Yes, we're using .net core. 
The email is coming from an invoicing system, and contains norwegian text. But don't know why they use this unusual encoding. I don't really need the text, the attachment and the email addresses is what I need, so maybe I'll have to try to strip it down before I parse it. Don't know if that's possible.

**Comment by Jericho** [comment]
Thinking out loud a few ideas, feel free to let me know what you think: 

**Idea 1:**
- What if the `ParseInboundEmailWebhook` and the `ParseInboundEmailWebhookAsync` methods allowed you to specify a "fallback" encoding which StrongGrid would use for decoding purposes when an "unusual" encoding is detected
- StrongGrid would use your fallback encoding to **attempt** (I repeat, **attempt**) to decode the content, keeping in mind that the result might be complete garbage if the encoding you specified is unable to handle the unusually encoded content.
- StrongGrid would be able to decode "From", "To" and "Subject" since they were encoded with a well-known encoding (UTF-8 in your example)
- This would mean that the "Text" property may or may not be successfully decoded (you said you didn't really care about the text anyway) but the other properties would be decoded as expected

**Idea 2:**
- Why even bother with asking developers to provide a fallback encoding? Why not simply assume UTF-8 whenever an unknown encoding is found?
- I'm pretty sure UTF-8 can decode most encoded content and "unknown" characters are simply replaced with the following:
![image](https://user-images.githubusercontent.com/112710/92793554-7f922580-f37c-11ea-8f5d-295b9a85ca23.png)

**Other thought:**
While we may figure out a solution for the email content, have you thought about the attachments generated by the invoicing system? Their content may also have been encoded with the "unusual" encoding and you will face the same problem when you try to read their content.

**Comment by BirgitteLoweJ** [comment]
I like idea 2! 

As for the attachment, thanks for pointing that out. I got an hold of the original email, and tested sending the attachment by itself, and that worked fine. The content looks good. So I think your idea will solve the problem.

**Comment by Jericho** [comment]
@BirgitteLoweJ Please let me know if the latest release solves this issue.

**Comment by BirgitteLoweJ** [comment]
@Jericho Just verified that the latest release solved the issue. Thanks alot!!
