### ISSUE TITLE
ParseInboundEmailWebhook fails: The specified string is not in the form required for an e-mail address

### ISSUE THREAD

**Issue by BirgitteLoweJ** [Jericho/StrongGrid#349]
Hi,
I get this error message when parsing inbound email: "The specified string is not in the form required for an e-mail address."
Have you seen this before? 

A clip from the header - with some censoring:

--xYzZY
Content-Disposition: form-data; name="to"

company@domain.no
--xYzZY
Content-Disposition: form-data; name="cc"

Firstname, Lastname <firstname.lastname@domain.com>
--xYzZY
Content-Disposition: form-data; name="from"

Firsname Lastname <firstname.lastname@domain.com>

**Comment by Jericho** [comment]
The three email addresses (`company@domain.no`, `Firstname, Lastname firstname.lastname@domain.com` and `Firsname Lastname firstname.lastname@domain.com`) in the snippet you provided seem perfectly valid so I suspect something else must be causing this problem. Can you provide a way to reproduce the problem? The best would be the JSON payload posted to you by SendGrid.

Having said that, I have seen [problems related to parsing email addresses](https://github.com/Jericho/StrongGrid/issues/332) which prevented the inbound webhook from being parsed but this problem was resolved in version 0.73.0. Maybe you are not using the latest version?

**Comment by Jericho** [comment]
Are you able to provide repro steps to help me investigate further?

**Comment by Jericho** [comment]
@BirgitteLoweJ I haven't heard back from you in a while so I'll go ahead and close this issue.
