### ISSUE TITLE
Error creating a CustomField Must provide a field type.

### ISSUE THREAD

**Issue by NewGio** [Jericho/StrongGrid#350]
hello,

 I am using this method to create a custom field:

strongGridClient.CustomFields.CreateAsync("BirthDay", FieldType.Text);

However, I am getting this error:

StrongGrid.Utilities.SendGridException: Must provide a field type.
   at Neworg.Process.EmailProcessor.Helpers.SendGridHelper.<CreateCustomField>d__24.MoveNext()

I am using the legacy client with StronGrid v0.71.0.0

I would appreciate any help

**Comment by Jericho** [comment]
I can't reproduce your exact scenario because when I attempt to use the legacy client to create a new custom field I get a `HTTP 403` "access forbidden". However, I am able to create custom fields without any problem using the new client so that's something you may want to think about.

One quick thing: you are invoking an async method so make sure you are awaiting the result like this:
```csharp
var newField = await strongGridClient.CustomFields.CreateAsync("BirthDay", FieldType.Text).ConfigureAwait(false);
```
I'm just curious: why are you still using the legacy client?

**Comment by Jericho** [comment]
@NewGio Have you been able to use the new client to workaround the problem?

**Comment by Jericho** [comment]
I haven't heard back so closing this issue.
