### ISSUE TITLE
Support sending a custom_dkim_selector when creating an authenticated domain

### ISSUE THREAD

**Issue by kevinchalet** [Jericho/StrongGrid#351]
Hey,

First of all, thanks a lot for this library, which is a gem compared to the "official" one 👏 

I have a scenario where I'd like to specify a custom `custom_dkim_selector` when creating a whitelabel/authenticated domain. Sadly, the `ISenderAuthentication.CreateDomainAsync()` method doesn't have such a parameter. Would adding it be an acceptable change?

If so, adding an optional parameter to an existing method is a binary (but not source) breaking change. How do you deal with that in StrongGrid?

Note: if it can help, I'd love to send a PR to help implement that 😃

**Comment by kevinchalet** [comment]
Note: in the same vein, you may also want to support the `username` parameter, that allows creating the authenticated domain under a subuser: https://sendgrid.api-docs.io/v3.0/domain-authentication/authenticate-a-domain

**Comment by Jericho** [comment]
> First of all, thanks a lot for this library, which is a gem compared to the "official" one 👏

I'm really glad you like StrongGrid and find it useful.

> I have a scenario where I'd like to specify a custom `custom_dkim_selector` when creating a whitelabel/authenticated domain. Sadly, the `ISenderAuthentication.CreateDomainAsync()` method doesn't have such a parameter. Would adding it be an acceptable change?

I suspect SendGrid added this parameter after I added the `CreateDomainAsync` method to the library. Sometimes they make changes to their API which they do not communicate so it's really hard for me to keep up with their changes. For example, if you search for "custom_dkim_selector" in their [release notes](https://sendgrid.com/docs/release-notes/), you won't find any mention of it.

> If so, adding an optional parameter to an existing method is a binary (but not source) breaking change. How do you deal with that in StrongGrid?

>  in the same vein, you may also want to support the username parameter, that allows creating the authenticated domain under a subuser

hummmmm, this is weird. This API method already supports the `on-behalf-of` header which is defined as `The subuser's username. This header generates the API call as if the subuser account was making the call`. I wonder what the difference is between the `on-behalf-of` header and the `username` parameter?

> adding an optional parameter to an existing method is a binary (but not source) breaking change. How do you deal with that in StrongGrid?

Under normal circumstances I deal with breaking changes by increasing the major version of my libraries but in the case of StrongGrid I haven't had the courage to tag it as "1.0.0" yet because I constantly find undocumented changes in their API so I simply increase the minor version (i.e.: 0.72.0, 0.73.0, 0.74.0 and so on). I do try to clearly identify releases that include breaking changes in my [release notes](https://github.com/Jericho/StrongGrid/releases). So, hopefully, such changes are easy to identify.

**Comment by Jericho** [comment]
Another change I will make to the `CreateDomainAsync` method: the `subdomain` parameter is currently required but SendGrid's documentation says that it's optional. Therefore, the parameter will be changed from `string subdomain` to `string subdomain = null`.

Also I noticed a problem with the UpdateDomainAsync method. See #353 for details.

**Comment by kevinchalet** [comment]
Awesome, thanks for your reply!

> Sometimes they make changes to their API which they do not communicate so it's really hard for me to keep up with their changes.

Yeah... I'm not really surprised 😅 

> hummmmm, this is weird. This API method already supports the `on-behalf-of` header which is defined as `The subuser's username. This header generates the API call as if the subuser account was making the call`. I wonder what the difference is between the `on-behalf-of` header and the `username` parameter?

Hum yeah, good point. I'll give it a try to see what happens when you try to use the OBO header with this API. I guess it's one of those inconsistencies we see in many places... (if I was mean, I'd say that's because of the horrible HR turnover 😅)

> I do try to clearly identify releases that include breaking changes in my [release notes](https://github.com/Jericho/StrongGrid/releases). So, hopefully, such changes are easy to identify.

👍 

Let me know if I can help in any way.

**Comment by Jericho** [comment]
@kevinchalet Are you able to help me test the release candidate I just published on [my MyGet feed](https://myget.org/feed/jericho/package/nuget/StrongGrid)?

**Comment by kevinchalet** [comment]
Thanks a lot! I can confirm this works like a charm! 👍

**Comment by Jericho** [comment]
Perfect. Thanks for validating. I will publish to NuGet momentarily.
