### ISSUE TITLE
Unable to get the from email

### ISSUE THREAD

**Issue by BirgitteLoweJ** [Jericho/StrongGrid#360]
Hi, we encountered an "out of the normal" way of formatting the from field in a received email: 
--xYzZY
Content-Disposition: form-data; name="from"

"Some text." "more text" \<email@test.no\>
--xYzZY

The ParseInboundEmailWebhook was not able to extract the 'From email' from this. Is this something you are able to help me with?

**Comment by Jericho** [comment]
Making sure I understand the situation:

I'm guessing that StrongGrid is able to parse the inbound email webhook **without** throwing an exception but it is unable to distinguish the email address of the sender from the name of the sender.

In other words, you get this:
![image](https://user-images.githubusercontent.com/112710/104955201-d3022900-5997-11eb-9f25-06fcf3345505.png)

but you would prefer something like this:
![image](https://user-images.githubusercontent.com/112710/104955527-5754ac00-5998-11eb-876d-ae4531b0f0b4.png)

Am I right?

The email address parsing logic was changed last year (see #323) in order to handle more scenarios and also to ensure that StrongGrid does not throw an exception when it can't handle the format of the address. We rely on `System.Net.Mail.MailAddress` to parse the string but in your scenario the format of the string seems to be completely non-standard. The solution would be to fallback to custom parsing logic (similar to what we had before last year's change) in cases where `System.Net.Mail.MailAddress` is unable to parse the string.

I'll work on a solution and post it to my MyGet feed. Hopefully you'll be able to test it and give me some feedback.

**Comment by Jericho** [comment]
Please give this a try and let me know if it slves your scenario: https://www.myget.org/feed/jericho/package/nuget/StrongGrid/0.76.0-improve-email-ad0052

**Comment by BirgitteLoweJ** [comment]
Yes, you are completely right. Very weird scenario, I don't know how they are able to send it that way. 

I tested your fix now, and it worked perfectly! Thank you, really appreciate your fast responses!

**Comment by Jericho** [comment]
Excellent. Thanks for the feedback. I will merge the fix and I intend to publish the next version this week along with a few other fixes.
