### ISSUE TITLE
SuppressionGroup.Id should be an int; not a long

### ISSUE THREAD

**Issue by jsgoupil** [Jericho/StrongGrid#365]
The SuppressionGroup.Id should be an integer. https://github.com/Jericho/StrongGrid/blob/develop/Source/StrongGrid/Models/SuppressionGroup.cs#L18
On their page, they flip-flop between "integer" and "number".

 * number: https://sendgrid.api-docs.io/v3.0/suppressions-unsubscribe-groups/retrieve-all-suppression-groups-associated-with-the-user
 * integer: https://sendgrid.api-docs.io/v3.0/suppressions-unsubscribe-groups/create-a-new-suppression-group

But in their C# library, it's a `int`.
https://github.com/sendgrid/sendgrid-csharp/blob/main/src/SendGrid/Helpers/Mail/Model/ASM.cs#L21

The `UnsubscribesCount` seems to be an int as well.

**Comment by Jericho** [comment]
The reason why I tend to prefer `long` over `int` for unique identifiers is because I have had problems with another project where I used `int` and eventually I started getting "overflow" exceptions when their numbers exceeded `int.MaxValue`. I also prefer `long` for properties that hold a "count" of something since I have no idea how large the value can get.

If `long` is causing an issue on your end, you can always cast it to an `int` (and hope that you never get an "overflow" exception!!!).

**Comment by jsgoupil** [comment]
You can probably keep that count an `int`. But the groupId it's an `int` from SendGrid. That's why. But I won't be unhappy if you don't fix it.
