### ISSUE TITLE
Support Google analytics settings on email send

### ISSUE THREAD

**Issue by terrysmith-fiworks** [Jericho/StrongGrid#386]
SendGrid supports sending Google analytics params for utm_source, utm_campaign, etc. at both the global level and on an individual send. StrongGrid only supports these settings at the global level with GoogleAnalyticsGlobalSettings.

We would love to see StrongGrid support these on a send in the GoogleAnalyticsSettings model. Currently we cannot send email campaigns concurrently because the campaign name is different for each. Global settings must be updated, a campaign sent, settings updated for the next campaign, etc. Plus, there is an issue with non-campaign-related emails going out at the same time and picking up the global settings and tracking params to which they shouldn't be tied! 

I believe this change would be nothing more than adding the utm properties already in GoogleAnalyticsSettings to GoogleAnalyticsGlobalSettings and, if set and Google tracking enabled, setting them on the /mail/send call.

Hope you'll consider this. Thank you!

**Comment by Jericho** [comment]
At the time I wrote the code for the `Mail` resource (late 2016 if I remember correctly), the Google Analytics settings at the individual send level were different than the global settings at least that's what SendGrid's documentation said. That's why I had to create two distinct classes: `GoogleAnalyticsSettings` and `GoogleAnalyticsGlobalSettings` and that's why at the individual level you can turn on Google Analytics but you can't set `utm_source`, `utm_medium`, etc.  Again, this is based on what I remember from 4 and half years ago, I could be wrong.

I just double checked their documentation on this subject and it looks like the settings are now the same at the global level and at the individual send level, exactly as you pointed out. 

This means that SrongGrid probably doesn't need two classes anymore and the `Mail` resource needs to be adjusted and allow you to set your GA settings.

I'll definitely include this improvement in the next release.

**Comment by terrysmith-fiworks** [comment]
THANK YOU! I greatly appreciate this change and your willingness to add it in so quickly. I suspected their API had changed over time.

**Comment by Jericho** [comment]
One detail that I had forgotten about is that there is a difference between the global GA settings and the settings at the individual send level: the property that allows you to turn these settings on or off is spelled differently:

In one case it's spelled "enabled"
![image](https://user-images.githubusercontent.com/112710/116261651-dac72b80-a745-11eb-9221-7a9eaa22b5d3.png)

and in the other case it's spelled "enable"
![image](https://user-images.githubusercontent.com/112710/116261760-f5010980-a745-11eb-968e-ba0108960d68.png)

Not a big problem for me to overcome, but it means that I will have to keep the two GA settings classes each with their own spelling for the JSON property that corresponds to the C# property (I had hoped to get rid of one of them and only keep a single class). 

In one case, the C# code will look like this:
```csharp
[JsonProperty(propertyName: "enabled")]
public bool Enabled { get; set; }
```

in the other case it will look like this:
```csharp
[JsonProperty(propertyName: "enable")]
public bool Enabled { get; set; }
```
