### ISSUE TITLE
SendToSingleRecipientAsync without replyTo broken since 0.83.0 (Support multiple reply-to addresses)

### ISSUE THREAD

**Issue by tmacht** [Jericho/StrongGrid#406]
I updated to 0.83.0. It seems that SendToSingleRecipientAsync does not work any more (I think only in the case that no replyTo address is specified). I had a quick look at the code and I suspect it is caused by the fact that a reply_to_list with a single element null is passed on to SendAsync.

We end up with the following exception:
StrongGrid.Utilities.SendGridException
Message: The reply_to_list object, when used, must at least have an email parameter and may also contain a name parameter

**Comment by Jericho** [comment]
You're right: we end up sending an array containing a null value to SendGrid's API which is why they complain about not providing at least one email. The correct thing to do is to omit the `reply_to_list` when a reply-to address is not specified by the developer.

I'll get that fixed. Thanks for reporting this issue.

**Comment by tmacht** [comment]
Thanks for the quick fix.
