### ISSUE TITLE
Assignment of data to dynamicdata fails

### ISSUE THREAD

**Issue by oliv0533** [Jericho/StrongGrid#441]
So, we recently upgraded from StrongGrid 0.84 to 0.89. 

We have a function that takes every property on an object and serializes it to JSON

```
var templateData = JObject.FromObject(
                request.MailModel,
                new JsonSerializer
                {
                    ContractResolver = new CamelCasePropertyNamesContractResolver()
                }); 
```

The model has these properties: 
```
public IRecipient Recipient { get; }
    public string TemplateId => "Redacted for security reasons";
    public IReadOnlyCollection<SendGridMailCategory> Categories { get; }
    public MailAddress Sender { get; }
    public IReadOnlyCollection<string> UserIds { get; }
    public List<MailAddress>? Bcc { get; set; }
    public MailAddress? ReplyTo { get; set; }
```

This data is then converted to a Dictionary<string, object> using 

```
var templateDataDictionary = templateData.ToObject<Dictionary<string, object>>();
```

This data is then added to a call using StrongGrid: 
```
var response = await _baseClient.Mail.SendToSingleRecipientAsync(
                        new MailAddress(to.Email, to.Name),
                        @from,
                        request.MailModel.TemplateId,
                        dynamicData: templateDataDictionary,
                        replyTo: request.MailModel.ReplyTo,
                        categories: request.MailModel.Categories.Select(x => x.ToString()),
                        cancellationToken: cancellationToken);
```

This used to work fine, but after the upgrade we have a problem regarding serialization of the IReadOnlyCollection containing userIds. The conversion from object to dictionary works normally, but somewhere in StrongGrids code, the collection disappears.

I have tested version 0.89, 0.88, 0.87 and 0.86. The bug is present on 0.87 and later, so i suspect it has something to do with the change from Newtonsoft.Json to System.Text.Json

**Comment by Jericho** [comment]
It's very possible that there's something a little different between Newtonsoft and System.Text.Json. I will be happy to investigate but I need you to provide a way for me to reproduce. Can you provide a unit test or at the very least, a code snippet?

Somewhat related to you scenario: I want to make you aware that I recently released an improvement that allows you to [specify how your dynamic data object is serialized](https://github.com/Jericho/StrongGrid/issues/440). Maybe this could help you avoid going through what seems to be convoluted gyrations:
1. MailModel -> string via Newtonsoft serialization
2. string -> Dictionary via 'ToObject'
3. passing this object to SendToSingleRecipientAsync which will serialize this dictionary using System.Text.Json

Just a thought.

**Comment by Jericho** [comment]
One more question: why do you even go through all these steps to convert your model to string, to dictionary, etc. Is there something fundamentally wrong with the way StrongGrid serializes dynamic data that prevents you from simply allowing the built-in serialization to take care of your model?

**Comment by Jericho** [comment]
Another question: have you identified the point in the process where the "collection disappears"? 

Is it when you convert your model into a string?
Is it when you convert the string into a dictionary?
Is it when your dictionary is serialized by StrongGrid?

**Comment by Jericho** [comment]
I was able to write a unit test to reproduce the scenario your described:

```csharp
// This is a simplified version of the model presented by @oliv0533 in GitHub issue #441
private class OriginalModel
{
	public IReadOnlyCollection<string> UserIds { get; set; }
}

[Fact]
public void Reproduce_the_original_problem()
{
	// This code reproduces the code presented by @oliv0533 in the GitHub issue
	var mailModel = new OriginalModel
	{
		UserIds = new ReadOnlyCollection<string>(new[] { "aaa", "bbb", "ccc" })
	};

	var templateData = JObject.FromObject(
		mailModel,
		new Newtonsoft.Json.JsonSerializer
		{
			ContractResolver = new CamelCasePropertyNamesContractResolver()
		});

	var templateDataDictionary = templateData.ToObject<Dictionary<string, object>>();


	// This code is a simplified version of the serialization logic in Mail.SendAsync
	var value = new MailPersonalization
	{
		DynamicData = templateDataDictionary,
		IsUsedWithDynamicTemplate = true
	};

	var ms = new MemoryStream();
	var jsonWriter = new Utf8JsonWriter(ms);
	var options = new JsonSerializerOptions();

	var converter = new MailPersonalizationConverter();

	converter.Write(jsonWriter, value, options);
	jsonWriter.Flush();

	ms.Position = 0;
	var sr = new StreamReader(ms);
	var result = sr.ReadToEnd();

	// The following assertion fails because we have reproduced the problem:
	result.ShouldBe("{\"dynamic_template_data\":{\"userIds\":[\"aaa\",\"bbb\",\"ccc\"]}}");
}
```

Instead of the expected `{\"dynamic_template_data\":{\"userIds\":[\"aaa\",\"bbb\",\"ccc\"]}}"`, your dynamic data is serialized as `"{\"dynamic_template_data\":{\"userIds\":[[],[],[]]}}"`. Just as you described, the content of the collection is lost.

The root of the problem is that you use Newtsonsoft to serialize your model to a string and then you use Newtonsoft again to deserialize this string into a dictionary where the type of each item is an object. **This detail is important.** The fact that you serialize into objects means that the serializer in System.Text.Json does not know the real type of each item and therefore it may or may not know how to serialize these items. This is important because the serializer needs to know the type of a given object in order to properly serialize it **in the most efficient way possible**. Newtonsoft is different in that respect: knowing the type of an object is not as critical because is uses a different method to figure out how to serialize a given object (I believe it uses reflection, but I'm not 100% certain). 

The bottom line is that this used to work because Newtonsoft didn't need to know the type of the items in your dictionary but it also means that it was much slower. The much improved performance and reduced memory usage is the main reason why I switched to System.Text.Json serializer. In case you are curious, I published some statistics that demonstrate the performance improvement: https://github.com/Jericho/StrongGrid/issues/402 I don't know why this problem only affects the "UserIds" property though. I'm guessing the fact that it's a more complex type (i.e.: IReadOnlyCollection<string>) has something to do with it.

All this to say, you need to discontinue this complicated serialization/deserialization process and you need to rely on the built-in serialization in order to overcome this problem. 

Having said that, I think I figured out why you implemented this complicated process: you want the casing of the property names to be different in the serialized data sent to SendGrid. For instance, you want the "UserIds" property to be serialized as "userIds" (lower case 'U'). The good news is that I have two suggestions that will allow you to achieved this goal:

**Suggestion number 1: Use the `JsonPropertyName` attribut to indicate the name of the property when serialized**
Since version 0.87.0 you could decorate your model class with a 'JsonPropertyName' that would allow you to control how the name of each property is serialized. Here's an example:
```csharp
[JsonPropertyName("userIds"]
public IReadOnlyCollection<string> UserIds { get; }

[JsonPropertyName("replyTo"]
public MailAddress? ReplyTo { get; set; }
```

FYI, you can also decorate a given property with the 'JsonIgnore' attribute if you don't want it to get serialized, like so:
```csharp
[JsonIgnore]
 public string TemplateId => "Redacted for security reasons";
```

This is, in my opinion, the easiest solution but I understand that you may not want to edit the definition of your model class for some reason, which means that this solution may not be appropriate for you. That's exactly why I recently implemented the new feature described in #440 which is my second suggestion.

**Suggestion number 2: Specify your desired serialization options**
This suggestion will require quite a bit of change in your code so it's a little more complex than my first suggestion but it will allow you to specify your desired "naming policy" among other serialization options. You will need to discontinue using the `SendToSingleRecipientAsync` and use the `SendAsync` method instead. This method is not as convenient because it requires you to specify more parameters, including an enumeration of "MailPersonalization", but the advantage is that you can specify the "DynamicDataSerializationOptions". Please you refer to #440 for a C# code sample demonstrating how to do this.

Let me know if either of my suggestions help.

**Comment by oliv0533** [comment]
Ah, i see, nice reproduction. 

You are completely correct about the reason for serializing og deserializing. We want the properties formatted. 

The first solution you specified would be verbose to implement, since it would need to be added to every mail template we have.
The second solution is much more promising. I will implement it this morning and report back

Thank you very much for your help so far!

**Comment by oliv0533** [comment]
I implemented your second suggestion and this worked perfectly. Thank you for your prompt assistance!
