### ISSUE TITLE
None of the models support being serialized

### ISSUE THREAD

**Issue by stephajn** [Jericho/StrongGrid#442]
When I use the serializer built into .NET, if I try to serialize a Webhook model, I get a NotImplementedException being thrown.

Upon digging into some of the converters that are written, I see that only the read method is implemented while the Write method just throws the exception. In my use case, I need to be able to deserialize the messages, but then I want to serialize them back again afterwards for storage and I can't do this.

Please implement the Write methods so that the models can be serialized.

**Comment by Jericho** [comment]
I'm having a hard time figuring out how `the serializer built into .NET` throwing `a NotImplementedException` is related to StrongGrid. Can you share a code snippet to illustrate your scenario?

**Comment by stephajn** [comment]
Looking at the source code of the StrongGrid.Models.WebHooks.Event class, I see that it used a custom converter called EventConverter to assist with serialization.

So when I look at the source code for EventConverter, I see it only implements the Read method, but the Write method literally just throws a NotImplementedException.

https://github.com/Jericho/StrongGrid/blob/develop/Source/StrongGrid/Json/EventConverter.cs

So, if I serialize any subclass of Event using the built in JSON serializer, of course it will throw when it tries to write any JSON strings.

If I serialize the class using JSON.NET, it doesn't throw at all because JSON.NET uses different serializer converters.

Here's my use case snippet.

```
WebhookParser webhookParser = new();
Event[] emailEvents = webhookParser.ParseEventsWebhook(serializedEvents);
string serializedEventString = JsonSerializer.Serialize(emailEvents);
```

NotImplementedException is thrown.

**Comment by Jericho** [comment]
Thanks for the snippet. It helped me understand your scenario.

First, let me try to explain why the StrongGrid library currently does not support your scenario:
The stated goal of the StrongGrid library is to make it easier for developers to interact with SendGrid's API and, more specifically, to transparently parse the JSON data returned from the API so that developers do not have to worry about the quirkiness of the data returned from SendGrid's API (trust me, there are a lot of quirks!). To that end, I have created several converters (16 converters, to be exact) which allow parsing the JSON payload returned from SendGrid's API into strongly typed objects (i.e.: models) and, in some cases, to serialize objects into JSON in order to POST this data back to SendGrid. To be specific: 10 of these serializer implement both Read and Write, 4 serializers implement Read only and 2 implement write only. The logic for implementing Read, Write or both was solely based on the need of the library and the goal was never to enable scenarios such as what you presented in your code snippet. In other words, it was never a goal to allow you to freely serialize and/or deserialize any of the models. In the your C# snippet, you attempt to re-serialize the array of "webhook events" which is not a scenario that the library has ever faced and therefore that explains why the `EventConverter` implements the Read method but not the Write method. I hope this clarifies the why you are getting an exception when you attempt to serialize the webhook events.

Having said all this, I think what you are trying to accomplish is perfectly reasonable and I can certainly review all the serializer classes to assess how much effort would be necessary to implement both Read and Write. At the bare minimum, implementing the Write method in the EventSerializer would probably be sufficient to enable your scenario.

Let me look into it and I'll report back when I have a better understanding of the scope of the work.

**Comment by stephajn** [comment]
Just to give a bit more understanding of the use case here:

I have an Azure Function that acts as the listener for SendGrid to call back to. The Azure Function's sole purpose is to look at the event, and then route it into an Azure Storage Queue for processing by another service for logging etc etc. So the goal is to parse the event(s) using StrongGrid, and then act on them based on the properties found inside and route them.

When they are being written to the Azure Storage Queue, they are written as is. On the opposite end of this chain is a service that listens to these Storage Queues, and again uses StrongGrid to deserialize these messages and act on them and process them.

So the serialization that needs to happen is when the message is being serialized into an Azure Storage Queue message's body.

I hope that helps understand the need for being able to deserialize but also to serialize them.

**Comment by Jericho** [comment]
I just published [the first beta of the library](https://www.myget.org/feed/jericho/package/nuget/StrongGrid/0.90.0-serialize-everyt0026) with serialization enabled for all model classes. 

I know there are at least two outstanding issues:
1. MailSettingsConverter and MailPersonalizationConverter do not support deserialization
2. Several unit test that are failing because they expect our custom Json converters to throw an exception when serializing (which is no longer the case)

I'm working on resolving these issues. In the mean time, maybe you could help me test the new functionality.

**Comment by Jericho** [comment]
Posted [another beta](https://www.myget.org/feed/jericho/package/nuget/StrongGrid/0.90.0-serialize-everyt0030) which resolves the two outstanding issues.

Let me know if you have an opportunity to test it.

**Comment by stephajn** [comment]
@Jericho I'll try it out and get back to you. Thanks for adding this!

**Comment by Jericho** [comment]
Thanks for the update. I'll prepare the release.
