### ISSUE TITLE
suppressionGroupId parameter in Campaigns.CreateAsync

### ISSUE THREAD

**Issue by jasneo** [Jericho/StrongGrid#46]
The parameter suppressionGroupId in Campaigns.CreateAsync should be nullable as the suppressionId CreateJObjectForCampaign is nullable.

I am unable to pass null value to it in order to create a campaign.

**Comment by Jericho** [comment]
The reason why the suppressionGroupId parameter is nullable in CreateJObjectForCampaign is because you can omit this value when updating a campaign.

The reason why the suppressionGroupId parameter in Campaign.CreateAsync is not nullable is because SendGrid does not allow you to send a campaign without a suppression group. If the StongGrid library allowed you to create a campaign without specifying a suppression group, you would get the following error from SendGrid when attempting to send the campaign:

`Please choose an unsubscribe group to use for any unsubscribes you receive for this campaign. Having an unsubscribe link in your campaign is required under CAN-SPAM, CASL, and other spam laws.`
