### ISSUE TITLE
Add .NET 7 and drop .NET 5

### ISSUE THREAD

**Issue by Jericho** [Jericho/StrongGrid#463]
.NET 7 targeted to be Released November 2022 replaces .NET 5 as [current](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core#cadence) release.

**Comment by vyrotek** [comment]
Hi @Jericho, When is this expected to be released? 

We believe we're running into issues with our .NET 7 app using this library which is still targeting .NET 6.

**Comment by ninjapiratica** [comment]
I work with @vyrotek and I'll give a few more specific details.

Yes, it is related to #476. We use dynamic templates and the DynamicData property is what is causing the issue. I don't know if .NET 7 targetting would solve it, or if your serializerOptions need to include the recommended action of adding the fallback as per the dotnet issue you referenced in #476  (https://github.com/dotnet/docs/issues/30755).

But since it looks like that property doesn't even exist in 6, .NET 7 might be needed to resolve the problem?

The DynamicData property can't be added as a [JsonSerializable] attribute since you don't know the type it will be, and when we tried adding our own TypeInfoResolver property on the DynamicDataSerializationOptions you provided, it didn't seem to work, giving the same error.

If you want, I can provide a sample project and open a new Issue fo the DynamicData property serialization to track it.

**Comment by Jericho** [comment]
Thanks for letting me know the problem was related to DynamicData. It allowed me to narrow down my investigation. Here's what I learned: 
- the root of the problem is not so much the fact that StrongGrid is targeting .net6
- the problem is due to the fact that your app targets .net7 which forces System.Text.Json version7 to be used (despite the fact that StrongGrid was built with a reference to System.Text.Json version6)
- System.Text.Json version 7 no longer falls back to reflection-based serialization by default (which is necessary to serialize dynamic data)
- The fact that reflection-based serialization is not used means that StrongGrid does not know how to serialization your dynamic data and therefore explains why you are getting a serialization exception

The fact that a different version of the Json serializer/deserializer is used depending on the version of .net used in your app explains why we see different behaviors/problems when an app targets .net7 (this fact eluded me for a long time and I'm glad I finally figured this out. It was bothering me that I was unable to explain why the behavior was different in .net6 vs .net7). However, changing StrongGrid to target .net7 would not resolve the problem you are experiencing. It would simply ensure that System.Text.Json version7 would always be used and therefore all developers would experience the same problem you are reporting, even when using .net6. At least the problem would be consistent no matter the version of .net!

All this to say that to solve the problem, I need to make two changes:
1. I need to upgrade System.Text.Json to version7
2. I need to indicate that I want to use reflection-based serialization when processing dynamic data

I might as well change the target frameworks to include .net7 and to drop .net5 at the same time but I want to be clear that it's neither the root of the problem nor the solution.

I published a beta version with these changes to [my MyGet feed](https://www.myget.org/feed/jericho/package/nuget/StrongGrid/0.96.0-target-dotnet-7-0025). give me some fedback when you have a chance to test it.

**Comment by ninjapiratica** [comment]
That beta version seems to work for our use cases. No noticeable issues in our testing.

**Comment by Jericho** [comment]
Thanks for confirming. I'll publish the new version to NuGet as soon as I have some free time (probably this weekend).

**Comment by vyrotek** [comment]
@Jericho Thank you!
