### ISSUE TITLE
StrongGrid v0.96 or above not working anymore on Azure Function In-process

### ISSUE THREAD

**Issue by Benjiiim** [Jericho/StrongGrid#490]
In a Visual Studio 2022 Azure Function project, .NET 6.0 (Long Term Support) which means In-process mode (and not Isolated worker process), with HTTP Trigger for example.
Add StrongGrid v0.95.1 => working properly when building and running in the emulator
Upgrade to StrongGrid v0.96 or above => `Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.` when running in the emulator
Upgrade Microsoft.NET.Sdk.Functions to last version => same behavior

Is there something we can do to use latest version of StrongGrid in .NET 6 In-process Azure Function?

**Comment by Jericho** [comment]
We faced this problem [before](https://github.com/Jericho/StrongGrid/issues/370). And other developers, completely unrelated to StrongGrid. have experienced this problem in Azure function too: [here](https://github.com/Azure/Azure-Functions/issues/1729), [here](https://github.com/Azure/azure-functions-core-tools/issues/2304), [here](https://stackoverflow.com/questions/74470489/system-io-filenotfoundexception-could-not-load-file-or-assembly-microsoft-exte/74473381#74473381) and [here](https://stackoverflow.com/questions/74744117/azure-function-v4-migration-could-not-load-file-or-assembly-microsoft-extensio). These are just a few examples, a quick Google search will help you find more examples of `Could not load file or assembly 'blablabla, Version=x.y.z` in Azure function.

I'm no Azure expect so take what I say with a grain of salt but here's my understanding of the problem: 
- the Azure function environment references some nuget packages (such as Microsoft.Extensions.Logging.Abstractions and Microsoft.Extensions.Options for example) which are one or two versions behind the latest that is publicly available on nuget
- your .NET project either directly or indirectly references a more recent version of the same nuget package. When I say indirectly, what I mean is that your project does not explicitly reference the package in question, but it references a package (StrongGrid in this instance) that itself references the problematic nuget package
- your .NET project is "in-process" which means that it runs in the same process as the Azure function environment and, as a consequence, can load only one version of a given nuget package
- the Azure environment is loaded first and therefore the older version of the nuget package in question is already loaded in memory by the time your .net project is loaded in memory. As a result, the more recent version of this package cannot be loaded. Hence the `Could not load file or assembly ...` error.

Have you tried using out-of-process (I think it's actually called "isolated" in Azure lingo, not 100% sure) rather than in-process? This would you the flexibility of referencing any nuget package without conflicting with the packages used by the Azure function environment. 

Another suggestion would be to upgrade to .NET 7. This [article](https://devblogs.microsoft.com/dotnet/dotnet-7-comes-to-azure-functions/#:~:text=You%20can%20now%20build%20your%20serverless%20applications%20with.NET,of.NET%2C%20more%20efficiently%20manage%20dependencies%20and%20service%20registration.) leads me to believe Azure function supports .NET 7. Hopefully, the .NET 7 Azure function environment references updated version of the nuget packages which does not conflict with StrongGrid.

However, I am pretty confident that you will find yourself in the exact same situation when Microsoft.Extension.Abstration version 8 is released and StrongGrid updates its references to this latest version. And again with each subsequent release of the nuget package until the Azure function is improved to work around the fact that .NET projects can reference more recent versions of the packages it also references

Finally, let me say that I realize StrongGrid is what exposed this problem to you, but I don't think it's the root of this problem. The root of the problem, based on my understanding of the situation, is that there is a nuget package version mismatch between the Azure environment and your project. In your case, this mismatch is caused by StrongGrid, I'll give you that, but you would have the exact same problem if your project directly referenced a nuget package that caused the mismatch. In fact, you can probably validate what I just said by attempting to publish a .NET project to Azure function with a direct reference to Microsoft.Extension.Logging.Abstraction version 7 (make sure your project **does not** reference StrongGrid) and you should experience the same `could not load ...` error.

Let me know if this helps.

**Comment by Benjiiim** [comment]
Thanks @Jericho for your detailed answer, that helps to confirm some unclear thoughts.
For your information, .NET 7 is indeed supported on Azure Function, but only in isolated worker process where the issue does not occur, for the exact reasons you've explained (https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v4%2Ccmd#supported-versions)
