### ISSUE TITLE
Exception is thrown when parsing webhook containing an unknow property with numerical data

### ISSUE THREAD

**Issue by Benjiiim** [Jericho/StrongGrid#491]
Are you aware of the reseller_id field that can be added in events sent to the event webhook when the Sendgrid account has been bought through a reseller such as Azure Marketplace?

This field is not (yet) documented on https://docs.sendgrid.com/for-developers/tracking-events/event but according to Sendgrid support:
"The reseller_id is an internal identifier for an account. The reseller_id will be identifying a specific subuser account.  The reseller_id is how the data gets identified with the specific account and that's why it was added."
"The reseller_id is identifying a specific this subuser account, therefore, it is added due to the nature of your SendGrid account". For example: "an Azure Reseller account".

As this field is an int, it is causing the ParseEventsWebhook method to fail with error "The JSON value could not be converted to StrongGrid.Models.Webhooks.Event[]".

What would be your suggestion to handle this properly?

**Comment by Jericho** [comment]
I am not aware of this field but I'm curious what investigative steps you took that led you to conclude that the mere presence of the reseller id field in the JSON document is causing the webhook parser to fail.

As far as I know, fields in a JSON document that do not have a corresponding field in the C# model are simply ignored and do not cause parsing to fail. But at this point, you have more information that I do about this situation so maybe there's something special about this scenario. 

Can you share the additional information that lead you to conclude the reseller_id was the culprit? For instance, can you share the JSON you receive from Zoom? Also, the full stack trace of the exception would be helpful.

I even wrote a contrived unit test that validates that the presence of this additional field in the JSON does not prevent our ability to parse the JSON:
```csharp
[Fact]
public void Successfully_parse_webhook_that_includes_reseller_id()
{
	const string JSON_WITH_RESELLER_ID = @"
	{
		""event"": ""meeting.created"",
		""payload"": {
			""account_id"": ""this is a test to verify that the presence of reseller_id does not prevent parsing the webhok event"",
			""reseller_id"": 1234
		},
		""event_ts"": 1617628462392
	}";

	var parsedEvent = (MeetingCreatedEvent)new WebhookParser().ParseEventWebhook(JSON_WITH_RESELLER_ID);

	parsedEvent.EventType.ShouldBe(EventType.MeetingCreated);
	parsedEvent.AccountId.StartsWith("this is a test");
}
```

Therefore I suspect the presence of this field is a red herring and there's some other issue that is causing the error your are facing. However, I won't be able to investigate any further until you provide more details.

**Comment by Jericho** [comment]
@Benjiiim do you intend to provide additional info so we can continue the investigation?

**Comment by Benjiiim** [comment]
Thanks @Jericho 
I need a few days before going back to this. Feel free to close the issue in the meantime if you prefer.
Thanks again.

**Comment by Jericho** [comment]
The unit test I previously wrote to try to reproduce the problem you are experiencing was invalid and led m to the wrong conclusion.

Here's a better unit test:

```csharp
[Fact]
public async Task Webhook_includes_reseller_id()
{
	const string JSON_WITH_RESELLER_ID = @"
	{
		""reseller_id"":1234,
		""email"":""example@test.com"",
		""timestamp"":1513299569,
		""smtp-id"":""<14c5d75ce93.dfd.64b469@ismtpd-555>"",
		""event"":""open"",
		""sg_machine_open"": false,
		""category"":""cat facts"",
		""sg_event_id"":""FOTFFO0ecsBE-zxFXfs6WA=="",
		""sg_message_id"":""14c5d75ce93.dfd.64b469.filter0001.16648.5515E0B88.0"",
		""useragent"":""Mozilla/4.0 (compatible; MSIE 6.1; Windows XP; .NET CLR 1.1.4322; .NET CLR 2.0.50727)"",
		""ip"":""255.255.255.255""
	}";

	// Arrange
	var responseContent = $"[{JSON_WITH_RESELLER_ID}]";
	var parser = new WebhookParser();
	using (var stream = GetStream(responseContent))
	{
		// Act
		var result = await parser.ParseEventsWebhookAsync(stream).ConfigureAwait(false);

		// Assert
		result.ShouldNotBeNull();
		result.Length.ShouldBe(1);
		result[0].GetType().ShouldBe(typeof(OpenedEvent));
	}
}
```

With this test I can reproduce the problem you are talking about:

```
 System.Text.Json.JsonException : The JSON value could not be converted to StrongGrid.Models.Webhooks.Event. 
---- System.InvalidOperationException : The requested operation requires an element of type 'String', but the target element has type 'Number'.
```

I was also able to pinpoint the root of this problem: the "reseller_id" is an unknown property and therefore it gets added to the `UniqueArguments` dictionary (it doesn't get ignored like I said in my prior [comment](https://github.com/Jericho/StrongGrid/issues/491#issuecomment-1558373735)). The keys and values in this dictionary must be strings but, as you mentioned in your original comment, "reseller_id" is numerical. This explains the `The requested operation requires an element of type 'String'` exception.

I'll get this fixed (the numerical value will have to be converted to text in order to be added the dictionary and I'll improve the assertion in the unit test like so:
```csharp
// Assert
result.ShouldNotBeNull();
result.Length.ShouldBe(1);
result[0].UniqueArguments.ShouldNotBeNull();
result[0].UniqueArguments.Count.ShouldBe(1);
result[0].UniqueArguments.ShouldContainKeyAndValue("reseller_id", "1234"); // Note that the value has been converted to a string
```

**Comment by Benjiiim** [comment]
Thanks a lot to have taken the time to go back to this to investigate more. :-)

**Comment by Benjiiim** [comment]
What about adding reseller_id as a property outside of the UniqueArguments dictionary?

**Comment by Jericho** [comment]
Changing the title of this issue to better reflect the fact that the root of this problem is not the reseller_id field per se, but rather the presence of any unknown property containing numerical data.

> What about adding reseller_id as a property outside of the UniqueArguments dictionary?

Do you mind raising a separate issue? We'll use this issue to track the bug that you found which prevents StrongGrig from dealing with unknown properties containing numerical data (not just reseller_id) and the new issue will be about adding a new property (just to prepare you though: I'm reluctant to do that). I'll be happy to ~~go on a rant and vent the frustration I went through over the years regarding the sh**show that is SendGrid's documentation of their event fields~~ share my reasoning for being cautious about modifying our webhook model classes.
