### ISSUE TITLE
Polymorphic Serialization?

### ISSUE THREAD

**Issue by elmalakai** [Jericho/StrongGrid#492]
I'm using StrongGrid for web hook integration. I parse the web hook, inspect it, make a decisions, and then want to serialize the strongly typed event to a string and queue it.

The simplest approach to do this results in the StrongGrid.Models.Webhooks.Event objects being serialized, and the strongly type event information being lost. 

I tried to to create a Polymorphic JsonTypeInfoResolver in my .net 7 project:
```csharp
 public class PolymorphicStrongGridEventTypeInfoResolver : DefaultJsonTypeInfoResolver
    {
        public override JsonTypeInfo GetTypeInfo(Type type, JsonSerializerOptions options)
        {

            JsonTypeInfo jsonTypeInfo = base.GetTypeInfo(type, options);

            Type baseSendGridType = typeof(StrongGridEvent);
            if (jsonTypeInfo.Type == baseSendGridType)
            {
                jsonTypeInfo.PolymorphismOptions = new JsonPolymorphismOptions
                {
                    TypeDiscriminatorPropertyName = "event",
                    IgnoreUnrecognizedTypeDiscriminators = false,
                    UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FailSerialization,
                    DerivedTypes =
                    {
                        new JsonDerivedType(typeof(BouncedEvent), EventType.Bounce.ToString().ToLower()),
                        new JsonDerivedType(typeof(ClickedEvent), EventType.Click.ToString().ToLower()),
                        new JsonDerivedType(typeof(DeferredEvent), EventType.Deferred.ToString().ToLower()),
                        new JsonDerivedType(typeof(DeliveredEvent), EventType.Delivered.ToString().ToLower()),
                        new JsonDerivedType(typeof(DroppedEvent), EventType.Dropped.ToString().ToLower()),
                        new JsonDerivedType(typeof(GroupResubscribeEvent), EventType.GroupResubscribe.ToString().ToLower()),
                        new JsonDerivedType(typeof(GroupUnsubscribeEvent), EventType.GroupUnsubscribe.ToString().ToLower()),
                        new JsonDerivedType(typeof(OpenedEvent), EventType.Open.ToString().ToLower()),
                        new JsonDerivedType(typeof(ProcessedEvent), EventType.Processed.ToString().ToLower()),
                        new JsonDerivedType(typeof(SpamReportEvent), EventType.SpamReport.ToString().ToLower()),
                        new JsonDerivedType(typeof(UnsubscribeEvent), EventType.Unsubscribe.ToString().ToLower()),
                    }
                };
            }

            return jsonTypeInfo;
        }

    }
```

But was unable to get it to work. 

Am I overthinking this? Is there a simple way to ask for the StrongGrid event to serialize as a strong typed class?

**Comment by Jericho** [comment]
I have never used type tnfo resolvers so I don't think I'll be able to help you with that. But wouldn't it be much simpler to rely on StrongGrid to deserialize the string after you retrieve it from your queueing system? Like what you are already doing to deserialize the data in a webhook? Here's what I have in mind:

**How to serialize an event.** 

At the risk of stating the obvious, you can serialize an event like so:

```csharp
// I am manually creating an event for simplicity sake.
// In your case, you get this event when you parse the Webhook data.
var myEvent = new BouncedEvent()
{
	InternalMessageId = "This is a test to investigate GH issue #492",
	Email = "test@whatever.com",
	... other properties omitted ...
};

// Assumption on my part: you are using System.Text.Json for serialization.
// You'll have to adjust the code below if you use a different serialization library
var serializedEventAsBinary = JsonSerializer.SerializeToUtf8Bytes(myEvent);
var serializedEventAsString = Encoding.UTF8.GetString(serializedEventAsBinary);
```

This will give you a string that looks something like this:
```
{"ip":null,"reason":null,"status":null,"tls":0,"type":"bounce","bounce_classification":"Unclassified","smtp-id":null,"category":null,"asm_group_id":null,"event":"bounce","email":"test@whatever.com","timestamp":-62135578800,"sg_event_id":null,"sg_message_id":"This is a test to investigate GH issue #492","MessageId":"This is a test to investigate GH issue #492","marketing_campaign_id":null,"marketing_campaign_name":null,"sg_user_id":null,"newsletter":null,"marketing_campaign_version":null,"marketing_campaign_split_id":null}
```

FYI: the string format of the serialized event matches the format as defined by the SendGrid API. This seemingly minor detail is actually quite important, I'll explain below.

This is the string you can queue. So far so good?

**How to deserialize the string**

Ok, now the challenge you face (based on my understanding of your scenario, feel free to correct me if I didn't quite get it), is when you retrieve the string from your queueing system and you want to deserialize it back to a strongly typed object. The challenge is due to the fact that none of the available serialization libraries (Microsoft's System.Text.Json, Newtonsoft's Json.net, etc.) know how to process this string. Remember the comment I made about the format of the serialized string? That's why I took the time to point it out. But the webhook parser included in StrongGrid knows how to process this string and convert it to a strongly typed object. So why not simply use it. In theory, something like this:

```csharp
var parser = new WebhookParser();
var result = parser.ParseEventsWebhook(stringRetrievedFromYouQueuingSystem);
```

But wait, not so fast. You have one final hurdle to clear: if you invoke `ParseEventsWebhook` like I just showed you, you'll actually get a `System.Text.Json.JsonException` with the following error message: `The JSON value could not be converted to StrongGrid.Models.Webhooks.Event[]`. The reason is for this is the SendGrid API states that webhooks events will be sent **AS AN ARRAY** but your string contains only a single event. This explains why the StrongGrid webhook parser does not know what to do and eventually throws an exception.

The solution is to "fake" an array by surrounding your string with the JSON characters that indicate where an array starts and ends. Something like this:

```csharp
var fakeArrayOfEvents = "[" + stringRetrievedFromYouQueuingSystem + "]";
var parser = new WebhookParser();
var result = parser.ParseEventsWebhook(fakeArrayOfEvents);
```

The result will be a variable (called 'result' in the code sample above) that contains an array of events and this array contains a single strongly typed item which, if I understood your scenario correctly, is what you are trying to achieve.

Hopefully this is helpful but let me know one way of another.

**Comment by elmalakai** [comment]
Thanks for the response.  Sorry I wasn't so clear. My issue is Serializing the 'strongly' types class, results in a string that looks like the Base class only (Event), and looses the strongly typed class properties:

```CSHARP
        [Fact]
        public async Task StoreSendGridEvents_ShouldSerializeNonBaseProperties()
        {
            // Arrange
            string rawJson = @"
            [{
                ""asm_group_id"": 12376,
                ""email"": ""test@test.com"",
                ""environment"": ""Production"",
                ""event"": ""click"",
                ""ip"": ""00.00.227.54"",
                ""majorDomoVersion"": ""2.1.0.0"",
                ""instanceId"": ""8ccb79f7-b8e7-49e7-9722-1222bb6fe123"",
                ""sg_event_id"": ""_4OIHQt4TQKwJV1234567"",
                ""sg_message_id"": ""T2bN-2iPRIi_1234yHoWsQ.filterdrecv-canary-dcfc8db9-hnrtr-1-12344EAD-74.0"",
                ""sg_template_id"": ""d-12344f397ba043c78d227670b2e2b389"",
                ""sg_template_name"": ""Template_Name"",
                ""timestamp"": 1684523009,
                ""url"": ""https://test.com/?id=ah4567ik3"",
                ""url_offset"": {
                  ""index"": 1,
                  ""type"": ""html""
                },
                ""useragent"": ""Snap URL Preview Service; bot; snapchat; https://developers.snap.com/robots"",
                ""EventPostTimestampUTC"": ""2023-05-19T19:03:37.8298975Z""
              }]
            ";

            byte[] byteArray = Encoding.UTF8.GetBytes(rawJson);
            MemoryStream eventsStream = new MemoryStream(byteArray);

            // Act
            WebhookParser webhookParser = new WebhookParser();
            var events = await webhookParser.ParseEventsWebhookAsync(eventsStream);

            //Should be 1
            Assert.True(events.Count() == 1);
            
            //Should be a ClickedEvent
            Assert.True(events[0].GetType().Name == typeof(ClickedEvent).Name);

            //Should have this URL
            Assert.Equal("https://test.com/?id=ah4567ik3", ((ClickedEvent)events[0]).Url);

            //Act 2 Serialize it
            var eventSerialized  = JsonSerializer.Serialize(events);

            System.Diagnostics.Debug.WriteLine(eventSerialized);
            //Should contain the Clicked URL:
            Assert.Contains("https://test.com/?id=ah4567ik3", eventSerialized);
        }

```
The eventSerialized looks like this:

```json
[{
    "event": "click",
    "email": "test@test.com",
    "timestamp": 1684523009,
    "sg_event_id": "_4OIHQt4TQKwJV1234567",
    "sg_message_id": "T2bN-2iPRIi_1234yHoWsQ.filterdrecv-canary-dcfc8db9-hnrtr-1-12344EAD-74.0",
    "MessageId": "T2bN-2iPRIi_1234yHoWsQ"
}]
```
So inside of 'BaseJsonConverter.Serialize()', it skips the derived properties. They come up as "propertyIsIgnored", and aren't serialized. I believe this function isn't properly serializing derived types and their properties. 

A work around:
I could iterate the array of events, and then switch on the event type and  JsonSerializer.Serialize<StrongEventType_HERE>(eventJson). Then stitch together the json back into an array, and queue it.

I don't mind doing that, but I just wanted to make sure I wasn't missing something simpler.

**Comment by Jericho** [comment]
Thanks for the additional information, I think I got it now.

Short term workaround: cast each event to their strong type when serializing. This will allow the serializer to properly serialize all the properties, not just the `Event` properties. Like in this example:
```csharp
//Act 2 Serialize it
var eventSerialized  = JsonSerializer.Serialize((ClickEvent)events[0]);
```

But I totally understand that this is not a long term solution since you don't necessarily know the type of each event. The better long term solution would be for `BaseJsonConverter` to properly detect the derived type when serializing an event (which I think is what you hinted at when you said that the base serializer `skips the derived properties`).

I'm looking into it...

**Comment by elmalakai** [comment]
Possibly you just implement the 'write' override in the EventConverter, and do nearly what the Read override does, but that would only help with Web Hook Events.

.Net 7 does improve this, with polymorphic deserialization, but would leave other SDK's behind.

**Comment by Jericho** [comment]
I'm fixing the problem and adding the following unit test to validate that we can serialize/desirialize wihtout loosing properties of derived types such as BouncedEvent, ClickedEvent and OpenEvent:

```csharp
[Fact]
// This unit test validates that we fixed the issue described in GH-492
// It proves that we can serialize and deserilize events without loosing
// properties of derived types such as 'Reason' for a bounced event,
// 'UserAgent' for a click event and 'IpAddress' for an open event.
public async Task Serialize_and_deserialize_derived_types()
{
	// Arrange
	var events = new Event[]
	{
		new BouncedEvent() { Email = "test1@whatever.com", Reason = "This is a test"},
		new ClickedEvent() { Email = "test2@whatever.com", UserAgent = "This is a test" },
		new OpenedEvent() { Email = "test3@whatever.com", IpAddress = "This is a test" }
	};

	// Act
	var serializedEvents = new MemoryStream(JsonSerializer.SerializeToUtf8Bytes(events));
	var result = await JsonSerializer.DeserializeAsync<Event[]>(serializedEvents).ConfigureAwait(false);

	// Assert
	result.ShouldNotBeNull();
	result.Length.ShouldBe(3);

	result[0].Email.ShouldBe("test1@whatever.com");
	result[0].EventType.ShouldBe(EventType.Bounce);
	((BouncedEvent)result[0]).Reason.ShouldBe("This is a test");

	result[1].Email.ShouldBe("test2@whatever.com");
	result[1].EventType.ShouldBe(EventType.Click);
	((ClickedEvent)result[1]).UserAgent.ShouldBe("This is a test");

	result[2].Email.ShouldBe("test3@whatever.com");
	result[2].EventType.ShouldBe(EventType.Open);
	((OpenedEvent)result[2]).IpAddress.ShouldBe("This is a test");
}
```

**Comment by elmalakai** [comment]
Looks like we're losing the 'UniqueArguments' dictionary on Event during the round strip serialize/deserialize/serialize. That's pretty unique to WebHookEvents. May just want to handle it in EventConverter:Write().

**Comment by Jericho** [comment]
Hummmm . I didn't think about that. `UniqueArguments` is decorated with `[JsonIgnore]` which causes it to be excluded from serialization which we want because the is no such thing as a `uniquearguments` node in the JSON document. But we want each item in the dictionary to be added to the JSON document. Probably need to override the `Write` method in event converter, as you suggested.
